name: lint
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: install pnpm
        run: npm install -g pnpm && pnpm install
      - name: Install
        run: pnpm install --no-frozen-lockfile
      - name: lint
        run: pnpm lint-staged 
      - name: type
        run: pnpm run lint:type
      - name: test
        run: pnpm run test 

 
      